---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  dev = "png", dpi = 300,
  fig.height = 3.5, 
  cache = TRUE
)
```

```{r, include = FALSE}
set.seed(1)
```

# quadroot

**quadroot** 
<!-- extends [**ggplot2**](https://github.com/tidyverse/ggplot2) providing -->
<!-- functions to visualize the decision spaces of classification and clustering methods. -->
<!-- **ggclassify** currently includes the functions `geom_classify()` and `geom_classify_boundary()` for plotting the classification regions through filling in the regions, or outlining the resulting -->
<!-- boundaries respectively. -->




## Installation

You can install the latest development version of **ggclassify** from [GitHub](https://github.com/) with:

``` r
if (!requireNamespace("remotes")) install.packages("remotes")
remotes::install_github("nathaniel-morgan/quadroot")
```



