# Generated by cpp11: do not edit by hand

fun <- function() {
  invisible(.Call(`_ggclassify_fun`))
}

collectdfc <- function(x) {
  .Call(`_ggclassify_collectdfc`, x)
}

quadpointsc <- function(df) {
  .Call(`_ggclassify_quadpointsc`, df)
}

seq2 <- function(startx, starty, length, n) {
  .Call(`_ggclassify_seq2`, startx, starty, length, n)
}
