# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

iso_c <- function(df) {
    .Call(`_biroot_iso_c`, df)
}

quad_point_c <- function(df) {
    .Call(`_biroot_quad_point_c`, df)
}

